In [2]:
import numpy as np 

X_test=np.array(([1,3,4],[1,4,5]))
X_train=np.array(([1,3,4],[1,4,5],[1,3,4],[1,4,5],[1,3,4]))

num_test = X_test.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train))
for i in xrange(num_test):
    for j in xrange(num_train):
        dists[i,j]=np.sqrt(np.sum(np.square(X_test[i,:]-X_train[j,:])))
        
print dists

np.random.randint(5)
    


    

[[ 0.          1.41421356  0.          1.41421356  0.        ]
 [ 1.41421356  0.          1.41421356  0.          1.41421356]]


1

In [271]:

aa=np.array(([1,3,4,6,7,8,9],[2,5,5,6,5,5,9],[5,3,4,6,4,8,9],[0,0,0,0,0,1,1]))
bb=np.sum(aa, axis=0, keepdims=False)
print bb, np.shape(bb)

print aa[range(3,2)]


[ 8 11 13 18 16 22 28] (7,)
[]


In [40]:
print aa
aa1=np.copy(aa)
print aa1

[[1 3 4 6 7 8 9]
 [2 5 5 6 5 5 9]
 [5 3 4 6 4 8 9]
 [3 3 4 6 7 4 9]]
[[1 3 4 6 7 8 9]
 [2 5 5 6 5 5 9]
 [5 3 4 6 4 8 9]
 [3 3 4 6 7 4 9]]


In [7]:
np.split(aa,2)

[array([[1, 3, 4, 6, 7, 8, 9],
        [2, 5, 5, 6, 5, 5, 9]]), array([[5, 3, 4, 6, 4, 8, 9],
        [3, 3, 4, 6, 7, 4, 9]])]

In [36]:
bb=[]
bb=np.split(aa,2)
print bb[0]

ss=[]
ss=np.concatenate((ss,bb[0]), axis=0)
ss


[[1 3 4 6 7 8 9]
 [2 5 5 6 5 5 9]]


ValueError: all the input arrays must have same number of dimensions

In [32]:
range(6)

[0, 1, 2, 3, 4, 5]

In [12]:
np.random.random_integers(5)

/Users/cihan_acar/Documents/ML/Python/cs231n/assignment1/.env/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  if __name__ == '__main__':


4

In [15]:
np.random()

TypeError: 'module' object is not callable

In [42]:
k=[0,4,3,8]
dic={}
dic[1]=[1,3,4]
dic[4]=[4,5]
dic

{1: [1, 3, 4], 4: [4, 5]}

In [47]:
dic[k[1]]=np.append(dic[k[1]],54)

In [48]:
dic

{1: [1, 3, 4], 4: array([ 4,  5,  5, 54, 54, 54, 54])}

In [5]:
 xx=[1,2,3,5,6]
it=np.nditer(xx, op_flags=['readwrite'])

TypeError: Iterator operand is flagged as writeable, but is an object which cannot be written back to via UPDATEIFCOPY

In [31]:
ff=np.array([[13,4],[4,5]])
gg=np.array([[2,4],[2,5]])

In [32]:
range()

2

In [33]:
ff[0,:]*gg[:,0]

array([26,  8])

In [36]:
gg.T

array([[2, 2],
       [4, 5]])

In [73]:

import numpy as np

ll=gg[0]*2
print ll
q=np.array(([5,6,7],[6,8,9]))
print q
q[:,0]=[x for x in ll]

[4 8]
[[5 6 7]
 [6 8 9]]


In [74]:
print q

[[4 6 7]
 [8 8 9]]


In [82]:
margins=np.array([23,4,0,4,0,12,0])
margins[:]=[x**0 for x in margins if x>0]



ValueError: cannot copy sequence with size 4 to array axis with dimension 7

In [81]:
print margins

[1, 1, 1, 1]


In [248]:
y=np.array([0,9])
scores=np.array(([1,8,2,7,8,7,5,7,2,5],[3,4,5,6,7,5,7,7,4,5]))

scores[range(2),y]=y
print scores

ff=scores[range(2),:]- scores[range(2),y].reshape(2,1)+1
print ff
ff[range(2),y]=0
print ff





[[0 8 2 7 8 7 5 7 2 5]
 [3 4 5 6 7 5 7 7 4 9]]
[[ 1  9  3  8  9  8  6  8  3  6]
 [-5 -4 -3 -2 -1 -3 -1 -1 -4  1]]
[[ 0  9  3  8  9  8  6  8  3  6]
 [-5 -4 -3 -2 -1 -3 -1 -1 -4  0]]


In [228]:
np.where(margins>0,1,0)

array([1, 1, 0, 1, 0, 1, 0])

In [122]:
rr=np.array([1,2,2])
ww=np.array([2,1,2,6])
print np.dot(ww.reshape(4,1),rr.reshape(1,3))

[[ 2  4  4]
 [ 1  2  2]
 [ 2  4  4]
 [ 6 12 12]]


In [129]:
train=np.array([[1,3,2],[8,3,5],[1,5,4],[1,3,8],[4,3,2]])
y=np.array([3,4,5,6,7])
batch=np.random.choice(train.shape[0],2)
train_batch=train[batch,:]
y_batch=y[batch]
print train_batch, y_batch

[[1 3 8]
 [4 3 2]] [6 7]


In [132]:
1e5*10

1000000.0

In [133]:
learning_rates = [1e-7, 5e-5]
len(learning_rates )

2

In [134]:
kk=[]

In [137]:
kk[0]=0.0

IndexError: list assignment index out of range

In [175]:
svms= np.array([[]])

In [176]:
svms= np.append(svms, [[7, 8, 9]])
print svms


[ 7.  8.  9.]


In [207]:
i=4 
j=3
results={}
results[i,j]=[2,4]
results[i+1,j+1]=[1,2]
print results
for x in results:
    print x[1]



{(5, 4): [1, 2], (4, 3): [2, 4]}
4
3


In [ ]:
  for i in xrange(num_train):
    scores = X[i].dot(W)  
    
    margins = np.maximum(0, scores - scores[y[i]] + 1)
    margins[y[i]] = 0
    loss+= np.sum(margins)
    n_margins=np.where(margins,1,0)
    dloss=np.sum(n_margins)
    dW[:,y[i]]+=[x for x in -X[i]*dloss] 
    dW+=np.dot(X[i].reshape(W.shape[0],1),n_margins.reshape(1,W.shape[1]))       

  loss /=num_train 
  loss += 0.5 * reg * np.sum(W * W)
  
  dW /= num_train  
  dW += reg *W 

In [268]:
print range(5,4)


[]
